title: Infinitely stacked
author: vivaan daga
email: your-email@domain.com
description: 

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
- posts.md
- github.md

footer_icons:
- username: Vivaan Daga
  url: https://math.stackexchange.com/users/789929/vivaan-daga
  icon: icon-mse.svg

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
